#setup
title: Advantec Global Services, Inc
tagline: ""
description: ""
url: "https://www.advantec.io"
baseurl: ""
timezone: "America/New_York"
permalink: pretty
author: agsi_jwilson
email: info@agsi.us
logo: /assets/img/logo2.svg
twitter:
  username: AdvantecUS
  card: summary
social:
  name: Advantec Global Services, Inc
  links:
    - https://twitter.com/advantecus
    - https://www.linkedin.com/company/advantec-global-services-inc

# Local Server
host: localhost

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

#compile style
sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - .sass-cache
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
