#setup
title: Advantec Global Services, Inc
email: info@agsi.us
description: ""
baseurl: ""
url: "https://www.advantec.us"
timezone: "America/New_York"
permalink: pretty

# Local Server
host: localhost

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

#compile style
sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - .sass-cache
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
