#setup
title: Advantec Global Services, Inc
description: "Advantec prides itself on providing world-class, senior Architects/Consultants for strategic consulting services to organizations across the globe. From rolling out new implementations and system upgrades, integrating some of the most complex projects, and being asked by name from Fortune 50 companies, Advantec is committed to delivering solutions from start to finish."
tagline: "Advantec has been providing turn-key virtualization and networking solutions for decades."
url: "https://www.advantec.us"
baseurl: ""
timezone: "America/New_York"
permalink: pretty
author: agsi_jwilson
email: info@agsi.us
logo: /assets/img/logo2.svg
twitter:
  username: AdvantecUS
  card: summary
social:
  name: Advantec Global Services, Inc
  links:
    - https://twitter.com/advantecus
    - https://www.linkedin.com/company/advantec-global-services-inc

# Local Server
host: localhost

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

#compile style
sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - .sass-cache
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
